// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/client/wallet.proto

package client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletRequest) Reset() {
	*x = WalletRequest{}
	mi := &file_proto_client_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletRequest) ProtoMessage() {}

func (x *WalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletRequest.ProtoReflect.Descriptor instead.
func (*WalletRequest) Descriptor() ([]byte, []int) {
	return file_proto_client_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *WalletRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type WalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      int64                  `protobuf:"varint,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletResponse) Reset() {
	*x = WalletResponse{}
	mi := &file_proto_client_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletResponse) ProtoMessage() {}

func (x *WalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletResponse.ProtoReflect.Descriptor instead.
func (*WalletResponse) Descriptor() ([]byte, []int) {
	return file_proto_client_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *WalletResponse) GetWalletId() int64 {
	if x != nil {
		return x.WalletId
	}
	return 0
}

type AccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      string                 `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	WalletId      int64                  `protobuf:"varint,2,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountRequest) Reset() {
	*x = AccountRequest{}
	mi := &file_proto_client_wallet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountRequest) ProtoMessage() {}

func (x *AccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_wallet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountRequest.ProtoReflect.Descriptor instead.
func (*AccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_client_wallet_proto_rawDescGZIP(), []int{2}
}

func (x *AccountRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *AccountRequest) GetWalletId() int64 {
	if x != nil {
		return x.WalletId
	}
	return 0
}

type AccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountResponse) Reset() {
	*x = AccountResponse{}
	mi := &file_proto_client_wallet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountResponse) ProtoMessage() {}

func (x *AccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_wallet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountResponse.ProtoReflect.Descriptor instead.
func (*AccountResponse) Descriptor() ([]byte, []int) {
	return file_proto_client_wallet_proto_rawDescGZIP(), []int{3}
}

func (x *AccountResponse) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

var File_proto_client_wallet_proto protoreflect.FileDescriptor

const file_proto_client_wallet_proto_rawDesc = "" +
	"\n" +
	"\x19proto/client/wallet.proto\x12\x06wallet\"(\n" +
	"\rWalletRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"-\n" +
	"\x0eWalletResponse\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\x03R\bwalletId\"I\n" +
	"\x0eAccountRequest\x12\x1a\n" +
	"\bcurrency\x18\x01 \x01(\tR\bcurrency\x12\x1b\n" +
	"\twallet_id\x18\x02 \x01(\x03R\bwalletId\"0\n" +
	"\x0fAccountResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId2\x91\x02\n" +
	"\rWalletService\x12=\n" +
	"\fCreateWallet\x12\x15.wallet.WalletRequest\x1a\x16.wallet.WalletResponse\x12@\n" +
	"\rCreateAccount\x12\x16.wallet.AccountRequest\x1a\x17.wallet.AccountResponse\x12=\n" +
	"\fDeleteWallet\x12\x15.wallet.WalletRequest\x1a\x16.wallet.WalletResponse\x12@\n" +
	"\rDeleteAccount\x12\x16.wallet.AccountRequest\x1a\x17.wallet.AccountResponseB\x1cZ\x1awalletService/proto/clientb\x06proto3"

var (
	file_proto_client_wallet_proto_rawDescOnce sync.Once
	file_proto_client_wallet_proto_rawDescData []byte
)

func file_proto_client_wallet_proto_rawDescGZIP() []byte {
	file_proto_client_wallet_proto_rawDescOnce.Do(func() {
		file_proto_client_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_client_wallet_proto_rawDesc), len(file_proto_client_wallet_proto_rawDesc)))
	})
	return file_proto_client_wallet_proto_rawDescData
}

var file_proto_client_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_client_wallet_proto_goTypes = []any{
	(*WalletRequest)(nil),   // 0: wallet.WalletRequest
	(*WalletResponse)(nil),  // 1: wallet.WalletResponse
	(*AccountRequest)(nil),  // 2: wallet.AccountRequest
	(*AccountResponse)(nil), // 3: wallet.AccountResponse
}
var file_proto_client_wallet_proto_depIdxs = []int32{
	0, // 0: wallet.WalletService.CreateWallet:input_type -> wallet.WalletRequest
	2, // 1: wallet.WalletService.CreateAccount:input_type -> wallet.AccountRequest
	0, // 2: wallet.WalletService.DeleteWallet:input_type -> wallet.WalletRequest
	2, // 3: wallet.WalletService.DeleteAccount:input_type -> wallet.AccountRequest
	1, // 4: wallet.WalletService.CreateWallet:output_type -> wallet.WalletResponse
	3, // 5: wallet.WalletService.CreateAccount:output_type -> wallet.AccountResponse
	1, // 6: wallet.WalletService.DeleteWallet:output_type -> wallet.WalletResponse
	3, // 7: wallet.WalletService.DeleteAccount:output_type -> wallet.AccountResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_client_wallet_proto_init() }
func file_proto_client_wallet_proto_init() {
	if File_proto_client_wallet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_client_wallet_proto_rawDesc), len(file_proto_client_wallet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_client_wallet_proto_goTypes,
		DependencyIndexes: file_proto_client_wallet_proto_depIdxs,
		MessageInfos:      file_proto_client_wallet_proto_msgTypes,
	}.Build()
	File_proto_client_wallet_proto = out.File
	file_proto_client_wallet_proto_goTypes = nil
	file_proto_client_wallet_proto_depIdxs = nil
}
